# Generated by Django 4.2.16 on 2024-11-22 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_counted_view_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 12, 8, 58, 601345, tzinfo=datetime.timezone.utc)),
        ),
    ]
