# Generated by Django 4.2.16 on 2025-01-20 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_alter_post_published_date_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 5, 15, 11, 59020, tzinfo=datetime.timezone.utc)),
        ),
    ]
