# Generated by Django 4.2.16 on 2025-01-20 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 5, 43, 54, 617380, tzinfo=datetime.timezone.utc)),
        ),
    ]
