# Generated by Django 4.2.16 on 2025-01-24 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 14, 54, 47, 121901, tzinfo=datetime.timezone.utc)),
        ),
    ]
