# Generated by Django 4.2.16 on 2025-01-28 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 14, 36, 30, 155955, tzinfo=datetime.timezone.utc)),
        ),
    ]
